import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api, RouterOutputs } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const {user} = useUser();
  if (!user) return null;
  console.log(user);

  return <div className="flex gap-3">
    <img src={user.profileImageUrl} alt="Profile image" className="h-16 w-16 rounded-full" />
    <input placeholder="Type some emojis!" className="grow bg-transparent" />
  </div>
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const {author, post} = props;
  return <div className="border-b border-slate-400 p-4 flex gap-3">
    <img src={author.profileImageUrl} className="h-16 w-16 rounded-full" />
    <div className="flex flex-col">
      <div className="flex text-slate-300">
        <span>@{author.username}</span>
      </div>
      <span>{`${post.content} · ${dayjs(post.createdAt).fromNow()}`}</span>
    </div>
  </div>
}

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();
  if (isLoading) return <div>Now loading...</div>;
  if (!data) return <div>No posts found!</div>;
  const {isSignedIn} = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full h-full border-x border-slate-400 md:max-w-3xl">
          <div className="flex border-b border-slate-400 p-3">
            {!isSignedIn && <SignInButton />}
            {isSignedIn && (
              <div className="flex justify-center">
                <CreatePostWizard />
                { /*<SignOutButton />*/ }
              </div>)
            }
          </div>
          <div className="flex flex-col">
            {data?.map(props => (
              <PostView key={props.post.id} {...props} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
